kind: Deployment
apiVersion: apps/v1
metadata:
  name: processor-api
  namespace: evolution
spec:
  selector:
    matchLabels:
      app: processor-api
  replicas: 1
  template:
    metadata:
      annotations:
        # dapr.io/enabled: "true"
        # dapr.io/app-id: "processor"
        # dapr.io/app-port: "80"
        # dapr.io/config: "tracing"
        # linkerd.io/inject: enabled
    spec:
      containers:
        - name: processor-api
          image: rohitrustagi007/evo_processor:0.1.0
          env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: AWS_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: access 
                key: AWS_ACCESS_KEY
          - name: AWS_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: secret 
                key: AWS_SECRET_KEY 
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m" 
    