apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: processor-api
  metrics-scraper: 'prom'
commonAnnotations:
  app: processor-api
bases:
  - ../../base
patchesStrategicMerge:
- deployment_patch.yaml