apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - appsettings.yaml
  - deployment.yaml
  #- hpa.yaml
  - service.yaml
  #- gateway.yaml
  #- canary.yaml
  #- service-monitor.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: appsettings
    namespace: processor
    files:
      - "appsettings.K8s.json"