apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-api-deployment
  namespace: evolution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-api
  template:
    metadata:
      labels:
        app: processor-api
    spec:
      containers:
      - name: processor-api
        image: rohitrustagi007/evo_processor:latest
        env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production" 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

