apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagestoreclaim
  namespace: processor
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi