apiVersion: v1
kind: PersistentVolume
metadata:
  name: imagestore
  namespace: processor
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"